/* auto-generated by napi-rs — do not edit */

/**
 * Return a seed derived from an optional user-supplied seed.
 * Passing undefined draws from OS entropy.
 */
export declare function makeSeed(seed?: number | undefined | null): number

/**
 * Generate `scale` entities using Monte Carlo sampling.
 *
 * `specsJson` is a JSON array of attribute spec objects, e.g.:
 *   [{"name":"age","type":"uniform_int","low":18,"high":80}, ...]
 *
 * Returns a JSON string (array of entity objects).
 */
export declare function generateEntities(seed: number, scale: number, specsJson: string): string
